/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ocjkqgdlejzjomjrahps"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jamtxZ2RsZWp6am9tanJhaHBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMDI5OTEsImV4cCI6MjA4ODg3ODk5MX0.AljoOhhSP2hDEg-9roksu-JutKUHQSNjcvHntvqbVUM"